<main>
	<div class="accolade a_ouvrante">
		<h2>Gameplay</h2>
		<p>
		Vous allez recevoir des demandes pour la difficulté et pour le nom du héros. Le nom du dragon (l'ennemi principal) est choisi aléatoirement dans une double-liste prédéterminée.<br>
		Votre aventure sera narrée dans une boite sur le bas de l'écran, tandis que pour avancer, vous devrez appuyer sur le bouton correspondant puis répondre aux demandes. <br>
		Votre but est de vaincre le dragon, mais cette tâche peut être rendue plus facile avec de l'équipement supérieur, obtenable à la forge contre un certain nombre de pièce d'or, récupérable dans la forêt ou à la vente d'objets que vous trouvez sur les cadavres de vos ennemis ou ceux déjà présents dans la forêt. Je vous conseille de passer voir le marchand à chaque fois que vous récupérez quelque chose.<br>
		Votre seul moyen de vous soigner sera de payer l'église ou l'auberge en ville, l'église coûtant plus cher.<br>
		Il se peut que vous rencontriez un "ami", lors de vos aventures en forêt. Vous ne gagnerez rien d'autre que des anecdotes de sa part, voire une blague de ma part.
	  </p>
	</div>
	<div class="accolade a_fermante">
		<h2>Histoire</h2>
		<p>
		Vous êtes un chevalier devenu mercenaire après la déchéance du duc à votre charge. Vous êtes un vétéran de combat... Certains disent que vous êtes trop vieux pour batailler, mais vos faits d'armes parlent pour vous encore aujourd'hui.<br>
		Des crieurs publics vous ont informé que la princesse a été enlevée et que sa main est à qui la délivrera. Vous savez que seul un dragon aurait pu faire ça pour que des crieurs publics l'annoncent, et vous décidez de vous diriger à la ville de Braie-sous-Mont pour y récolter la gloire d'une chasse au dragon.<br>
		Cette drôle de ville, dont le mur ouest fait partie de l'immense frontière entre le royaume et un espace inconnu de tous sauf quelques élites, dont vous ne faîtes pas partie, a par contre l'avantage d'être prolifique et avec suffisament de possibilités autour pour une meilleure chasse au dragon.<br>
		Aussitôt arrivé, le maire vous souhaite la bienvenue et vous demande votre nom, avant de vous révéler le nom du dragon qui terrorise la ville depuis bien avant l'enlèvement de la princesse...
	  </p>
		<br>
	</div>
	<div class=visuel>
  	<a href= "login.php"><button class="nextButton onlyButton" name="button1">Aventure, <br>en avant !</button></a>
	</div>
</main>
