<!DOCTYPE html>

<html lang="fr">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>The princess needs you</title>
	<link type="text/css" rel="stylesheet" href="css/normalize.css">
	<link type="text/css" rel="stylesheet" href="css/hero.css">
</head>
<body>
	<header>
		<h1>SAUVEZ LA PRINCESSE !!!</h1>
	</header>
		<!-- utilisation du contenu spécifique à la page envoyé par le php -->
	  <?php include $template . ".phtml" ?>

</body>
</html>
