<main>
	<section class="finaleP">
		<article id="image">
			<img src="images/corpse_cave.jpg">
		</article>
		<div>
			<p class="avertissement">Aujourd'hui, vous avez vaincu le dragon <?=$GameVictory?> fois et été vaincu <?=$GameDefeat?> fois.</p>
			<p>Au total, vous avez vaincu le dragon <?=$victory?> fois et été vaincu <?=$defeat?> fois.</p>
			<p class="avertissement">Bel effort !</p>
			<p>Toutes ces aventures que votre âme a vécu vous ont finalement permis de reposer en paix... </p>
			<p>Au fond de la cave du dragon, son squelette autour de celui de la princesse que vous êtiez.</p>
		</div>
		<div>
		<a href= "index.php"><button class="nextButton" name="button1">Commencer une nouvelle aventure ?</button></a>
	</div>
	</section>
</main>
