<main>
	<section class="jeu_en_cours">
		<div class="pt_vie affich_jeu" id="Chevalier">
			<h3>
				Chevalier PV :
			</h3>
			<p id="KHP">
			</p>
		</div>

		<div class="image_descri affich_jeu" id="ImageDescr">
			<img src="images/dragon.jpg" alt="accueil de la ville">
		</div>

		<div class="argent affich_jeu" >
			<h3>
				Votre argent :
			</h3>
			<p id="Gold">
			</p>
		</div>
	</section>

	<section class="recit">
		<div>
			<button id="button" class="go_button" onclick="travel()" >
				Continuer
			</button>
		</div>
		<div id="LogAction">
		</div>

	</section>
</main>
<footer>
	<script type="text/javascript" src='fonctionalities/utilities.js'></script>
	<script type="text/javascript" src='fonctionalities/game.js'></script>
</footer>
